import JSZip from 'jszip'
import { readFile } from 'fs/promises'
import path from 'path'
import { prisma } from '@/lib/prisma'
import { connectToMongoDB } from '@/lib/mongoose'
import { SubmissionData } from '@/models/SubmissionData'
import { DynamicForm } from '@/models/DynamicForm'
import { NextResponse } from 'next/server'

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params

    // ── 1. PostgreSQL: relational data ──────────────────────────────────────
    const application = await prisma.applicationStatus.findUnique({
      where: { id },
      include: { program: true, user: true },
    })
    if (!application) {
      return NextResponse.json({ error: 'Application not found' }, { status: 404 })
    }

    // ── 2. MongoDB: submission data + form schema ───────────────────────────
    await connectToMongoDB()
    const [submission, formSchema] = await Promise.all([
      SubmissionData.findOne({ applicationStatusId: id }).lean(),
      DynamicForm.findOne({ programId: application.programId }).lean(),
    ])

    // ── 3. Build field-name → label map (preserving field order) ───────────
    const fieldMeta: { name: string; label: string; type: string }[] =
      formSchema?.fields ?? []
    const labelOf = (name: string) =>
      fieldMeta.find(f => f.name === name)?.label ?? name

    // ── 4. Generate application-summary.txt ────────────────────────────────
    const hr = '─'.repeat(56)
    const lines: string[] = [
      'APPLICATION SUMMARY',
      '═'.repeat(56),
      `Generated : ${new Date().toUTCString()}`,
      `Application ID : ${application.id}`,
      '',
      'PROGRAM',
      hr,
      `Name        : ${application.program.name}`,
      `Type        : ${application.program.type}`,
      `University  : ${application.program.university}`,
      '',
      'APPLICANT',
      hr,
      `Name   : ${application.user.name}`,
      `Email  : ${application.user.email}`,
      '',
      'STATUS',
      hr,
      `Current Status : ${application.status}`,
      `Created        : ${application.createdAt.toUTCString()}`,
      `Last Updated   : ${application.updatedAt.toUTCString()}`,
      '',
      'FORM ANSWERS',
      hr,
    ]

    const answers = (submission?.answers ?? {}) as Record<string, unknown>

    // Write answers in the original field order from the form schema
    for (const field of fieldMeta) {
      if (field.type === 'file') continue   // files go in the documents section
      const value = answers[field.name]
      if (value !== undefined && value !== '') {
        lines.push(`${field.label}`)
        lines.push(`  ${String(value).replace(/\n/g, '\n  ')}`)
        lines.push('')
      }
    }
    // Catch any answers not in the schema (schema may have changed)
    for (const [key, value] of Object.entries(answers)) {
      const inSchema = fieldMeta.some(f => f.name === key)
      if (!inSchema && value !== undefined && value !== '') {
        lines.push(`${key}`)
        lines.push(`  ${String(value)}`)
        lines.push('')
      }
    }

    const documents = submission?.documents ?? []
    if (documents.length > 0) {
      lines.push('UPLOADED DOCUMENTS', hr)
      documents.forEach((doc, i) => {
        lines.push(`${i + 1}. ${labelOf(doc.fieldName)} — ${doc.fileName}`)
        lines.push(`   Stored at: ${doc.fileUrl}`)
      })
      lines.push('')
    }

    lines.push('═'.repeat(56))
    lines.push('Generated by StudentApply')

    const summaryText = lines.join('\n')

    // ── 5. Build ZIP ────────────────────────────────────────────────────────
    const zip = new JSZip()
    zip.file('application-summary.txt', summaryText)

    if (documents.length > 0) {
      const docsFolder = zip.folder('documents')!
      for (const doc of documents) {
        const absPath = path.join(process.cwd(), 'public', doc.fileUrl)
        try {
          const buf = await readFile(absPath)
          // Organise by field name so files from different fields don't collide
          docsFolder.folder(doc.fieldName)!.file(doc.fileName, buf)
        } catch {
          // File missing on disk — leave a note rather than failing the whole download
          docsFolder.folder(doc.fieldName)!.file(
            `MISSING_${doc.fileName}.txt`,
            `This file was not found on the server.\nExpected path: ${doc.fileUrl}\n`
          )
        }
      }
    }

    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    })

    const safeName = (s: string) => s.replace(/[^a-zA-Z0-9]/g, '_')
    const filename = `application_${safeName(application.user.name)}_${safeName(application.program.name)}.zip`

    return new Response(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(zipBuffer.length),
      },
    })
  } catch (err) {
    console.error('[GET /api/applications/[id]/download]', err)
    return NextResponse.json({ error: 'Failed to generate download package' }, { status: 500 })
  }
}
